modLoader = "javafml" #mandatory

loaderVersion = "${loader_version_range}" #mandatory

license = "${mod_license}"

[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${mod_version}" #mandatory
displayName = "${mod_name}" #mandatory
description = '''
Example mod description.
'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[mixins]]
config = "simple_animator.mixins.json"

[[dependencies.${ mod_id }]] #optional
modId = "neoforge" #mandatory
type = "required" #mandatory
versionRange = "[${neo_version},)" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
